/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZodiacRouteImport } from './routes/zodiac'
import { Route as FiveElementsRouteImport } from './routes/five-elements'
import { Route as DailyFortuneRouteImport } from './routes/daily-fortune'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as IndexRouteImport } from './routes/index'

const ZodiacRoute = ZodiacRouteImport.update({
  id: '/zodiac',
  path: '/zodiac',
  getParentRoute: () => rootRouteImport,
} as any)
const FiveElementsRoute = FiveElementsRouteImport.update({
  id: '/five-elements',
  path: '/five-elements',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyFortuneRoute = DailyFortuneRouteImport.update({
  id: '/daily-fortune',
  path: '/daily-fortune',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/daily-fortune': typeof DailyFortuneRoute
  '/five-elements': typeof FiveElementsRoute
  '/zodiac': typeof ZodiacRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/daily-fortune': typeof DailyFortuneRoute
  '/five-elements': typeof FiveElementsRoute
  '/zodiac': typeof ZodiacRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compatibility': typeof CompatibilityRoute
  '/daily-fortune': typeof DailyFortuneRoute
  '/five-elements': typeof FiveElementsRoute
  '/zodiac': typeof ZodiacRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compatibility'
    | '/daily-fortune'
    | '/five-elements'
    | '/zodiac'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compatibility' | '/daily-fortune' | '/five-elements' | '/zodiac'
  id:
    | '__root__'
    | '/'
    | '/compatibility'
    | '/daily-fortune'
    | '/five-elements'
    | '/zodiac'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompatibilityRoute: typeof CompatibilityRoute
  DailyFortuneRoute: typeof DailyFortuneRoute
  FiveElementsRoute: typeof FiveElementsRoute
  ZodiacRoute: typeof ZodiacRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zodiac': {
      id: '/zodiac'
      path: '/zodiac'
      fullPath: '/zodiac'
      preLoaderRoute: typeof ZodiacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/five-elements': {
      id: '/five-elements'
      path: '/five-elements'
      fullPath: '/five-elements'
      preLoaderRoute: typeof FiveElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-fortune': {
      id: '/daily-fortune'
      path: '/daily-fortune'
      fullPath: '/daily-fortune'
      preLoaderRoute: typeof DailyFortuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompatibilityRoute: CompatibilityRoute,
  DailyFortuneRoute: DailyFortuneRoute,
  FiveElementsRoute: FiveElementsRoute,
  ZodiacRoute: ZodiacRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
