/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZodiacRouteImport } from './routes/zodiac'
import { Route as FiveElementsRouteImport } from './routes/five-elements'
import { Route as IndexRouteImport } from './routes/index'

const ZodiacRoute = ZodiacRouteImport.update({
  id: '/zodiac',
  path: '/zodiac',
  getParentRoute: () => rootRouteImport,
} as any)
const FiveElementsRoute = FiveElementsRouteImport.update({
  id: '/five-elements',
  path: '/five-elements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/five-elements': typeof FiveElementsRoute
  '/zodiac': typeof ZodiacRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/five-elements': typeof FiveElementsRoute
  '/zodiac': typeof ZodiacRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/five-elements': typeof FiveElementsRoute
  '/zodiac': typeof ZodiacRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/five-elements' | '/zodiac'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/five-elements' | '/zodiac'
  id: '__root__' | '/' | '/five-elements' | '/zodiac'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FiveElementsRoute: typeof FiveElementsRoute
  ZodiacRoute: typeof ZodiacRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zodiac': {
      id: '/zodiac'
      path: '/zodiac'
      fullPath: '/zodiac'
      preLoaderRoute: typeof ZodiacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/five-elements': {
      id: '/five-elements'
      path: '/five-elements'
      fullPath: '/five-elements'
      preLoaderRoute: typeof FiveElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FiveElementsRoute: FiveElementsRoute,
  ZodiacRoute: ZodiacRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
